//
//  KizuIcons.h
//  Kizu
//
//  Created by James Cryer on 11/07/2015.
//  Copyright (c) 2015 JC Web. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface KizuIcons : NSObject

// Drawing Methods
+ (void)drawDashboardWithRect: (CGRect)rect;
+ (void)drawPieWithRect: (CGRect)rect;
+ (void)drawAddUserWithRect: (CGRect)rect;
+ (void)drawUserWithRect: (CGRect)rect;
+ (void)drawTeamWithRect: (CGRect)rect;
+ (void)drawBellWithRect: (CGRect)rect;
+ (void)drawSearchWithRect: (CGRect)rect;
+ (void)drawProjectsWithRect: (CGRect)rect;
+ (void)drawFolderWithRect: (CGRect)rect;
+ (void)drawMonitorWithRect: (CGRect)rect;
+ (void)drawPlusWithRect: (CGRect)rect;
+ (void)drawCogWithRect: (CGRect)rect;
+ (void)drawCloudWithRect: (CGRect)rect;
+ (void)drawWifiWithRect: (CGRect)rect;
+ (void)drawTrashWithRect: (CGRect)rect;
+ (void)drawHomeWithRect: (CGRect)rect;
+ (void)drawGraphWithRect: (CGRect)rect;
+ (void)drawMessageWithRect: (CGRect)rect;
+ (void)drawPictureWithRect: (CGRect)rect;
+ (void)drawAToZWithRect: (CGRect)rect;
+ (void)drawLargeBrushWithFrame: (CGRect)frame;
+ (void)drawMediumBrushWithFrame: (CGRect)frame;
+ (void)drawSmallBrushWithFrame: (CGRect)frame;
+ (void)drawAnnotationWithFrame: (CGRect)frame;
+ (void)drawTextWithFrame: (CGRect)frame;
+ (void)drawDeleteWithFrame: (CGRect)frame;
+ (void)drawEraseWithFrame: (CGRect)frame;
+ (void)drawAddWithFrame: (CGRect)frame;
+ (void)drawUndoWithFrame: (CGRect)frame;

@end
